events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/', views.add_event, name='addEvent'),
    url(r'^logout', views.logout_request, name='logout'),
    url(r'^delete/(?P<idEvent>\d+)$', views.delete_event, name='deleteEvent'),
    url(r'^signUp/', views.signUp, name='signUp'),
    url(r'^edit/(?P<idEvent>\d+)$', views.edit_event, name='editEvent'),
]

projectABC/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('events.urls', namespace='events')),
]

events/models.py
from django.db import models
from django.forms import ModelForm, Form, CharField, TextInput, EmailField, PasswordInput, DateInput
from django.contrib.auth.models import User
from django import forms
from projectABC import settings
from datetime import date

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.name

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']

class Event(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    place = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=1000, null=True)
    initialDate = models.DateField(default=date.today)
    finalDate = models.DateField(default=date.today)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return 'Event: ' + self.name

class EventForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    place = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    address = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    initialDate = forms.DateField(initial=date.today, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type':'date'}
    ))
    finalDate = forms.DateField(initial=date.today, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type':'date'}
    ))

    class Meta:
        model = Event
        fields = ['name', 'category', 'place', 'address', 'initialDate', 'finalDate']

    def save(self, user):
        obj = super().save(commit=False)
        obj.user = user
        obj.save()
        return obj


class SignInForm(Form):
    username = CharField(max_length=50, widget=TextInput(
        attrs={'class': 'form-control'}
    ), required=True)
    password = CharField(min_length=8, max_length=10, widget=PasswordInput(
        attrs={'class': 'form-control'}
    ), required=True)

events/views.py
from django.shortcuts import render, redirect
from .models import Event, EventForm, User, Category, SignInForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def index(request):
    events_list = Event.objects.all()
    error = ''
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                error = ''
                return HttpResponseRedirect(reverse('events:index'))
            else:
                error = 'Username or password not correct'
        else:
            form = SignInForm()
    else:
        form = SignInForm()

    context = {'events_list': events_list,
               'form': form, 'error': error}
    return render(request, 'events/index.html', context)

def add_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(request.user)
            return HttpResponseRedirect(reverse('events:index'))
    else:
        form = EventForm()

    return render(request, 'events/event_form.html', {'form': form})


def logout_request(request):
    logout(request)
    return redirect('events:index')

def delete_event(request, idEvent=None):
    Event.objects.filter(id=idEvent).delete()
    return redirect('events:index')

def signUp(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        print('inicio')
        if form.is_valid():
            print('form valido')
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('events:index')
    else:
            form = UserCreationForm()

    return render(request, 'events/register_form.html', {'form': form})


def edit_event(request, idEvent=None):
    event = Event.objects.get(id=idEvent)

    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save(request.user)
            return HttpResponseRedirect(reverse('events:index'))
    else:
        form = EventForm(instance=event)
        context={'form':form, 'event':event}

    return render(request, 'events/editEvent.html', context)

events/templates/events/editEvent.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Multimedia Gallery</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
        crossorigin="anonymous">
</head>

<body style="background-color:#f0f0f0; overflow-x: hidden; width: 100%">
    <div class="row">
        <div class="col-lg-8 col-md-10 col-12 mx-auto">
            <div class="card mx-auto mt-5 shadow-lg border border-dark">
                <div class="card-header text-center text-white bg-dark">
                    <h3>Event</h3>
                </div>
                <div class="card-body">
                    <form action="{% url 'events:editEvent' event.id %}" name="eventDetails" id="eventForm" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" value="{{event.name}}" />
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <input type="text" class="form-control" value="{{event.category}}" />
                        </div>
                        <div class="form-group">
                            <label for="place">Place</label>
                            <input type="text" class="form-control" value="{{event.place}}"/>
                        </div>
                        <div class="form-group">
                            <label for="address">Address</label>
                            <input type="text" class="form-control" value="{{event.address}}"/>
                        </div>
                        <div class="form-group">
                            <label for="initialDate">Initial Date</label>
                            <input type="date" class="form-control" value="{{event.initialDate}}"/>
                        </div>
                        <div class="form-group">
                            <label for="finalDate">Final Date</label>
                            <input type="date" class="form-control" value="{{event.finalDate}}" />
                        </div>
                        <div class="text-center">
                            <button class="btn btn-success" type="submit"><i class="fas fa-save"></i>&nbsp;Edit
                                event</button>
                        </div>
                    </form>
                    {% if error != '' %}
                    <hr />
                    <div class="alert alert-danger text-center small" role="alert">
                        {{error}}
                    </div>
                    {% endif %}
                </div>

            </div>

        </div>

        <div class="col-12">
            <br />
            <br />
        </div>

    </div>




</body>

</html>

events/templates/events/event_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add an Event</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
</head>

<body>
    <div class="bg-dark">
        <h1 class="text-center pt-2 pb-2" style="font-family: fantasy; color: white">Add a new Event</h1>
    </div>
    <br />
    <div class="container center">
        {% block content %}
        <form action="{% url 'events:addEvent' %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <br />
            <div class="text-center">
                <input class="btn btn-primary" type="submit" value="Add Event">
            </div>
            <br />
        </form>
        {% endblock %}
    </div>
</body>

</html>

events/templates/events/index.html
{% load static %}<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Events handling</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossorigin="anonymous">
</head>

<body style="background-color:#f0f0f0; overflow-x: hidden; width: 100%">
    <div class="bg-dark">
        <h1 class="text-center pt-2 pb-2" style="font-family: fantasy; color: white">Events handling</h1>
    </div>
    <br />

    <div class="row" style="display: flex; align-items: center;">
        <div class="col-12">
            <br />
        </div>
        {% if user.is_authenticated %}
        <div class="col-lg-4">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle shadow m-3" type="button" id="dropdownMenuLoggedIn"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i>&nbsp;{{user.first_name}}
                </button>
                <div class="dropdown-menu dropdown-menu-right border border-secondary" aria-labelledby="dropdownMenuLoggedIn">
                    <a class="dropdown-item" href="{% url 'events:logout' %}"><i class="fas fa-sign-out-alt"></i>&nbsp;Log out</a>
                </div>
            </div>
        </div>
        <div class="col-12 text-center">
            <a class="text-white btn btn-primary m-2 shadow" href="{% url 'events:addEvent' %}"><i class="fas fa-plus"></i>&nbsp;Add
                event
            </a>
        </div>
        {% for event in events_list %}
        {% if event.user.id == user.id %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-12 mb-4">
            <div class="card border-success mx-auto shadow" style="max-width: 18rem;">
                <div class="card-header">
                    <a href="edit/{{event.id}}">
                        <i class="far fa-edit text-secondary"></i>
                    </a>
                    <a class="close" href="delete/{{event.id}}">
                        <i class="far fa-window-close text-danger"></i>
                    </a>
                </div>
                <div class="card-body">
                    <h5 class="card-title mt-2">{{event.name}}</h5>
                    <p class="card-text">
                        <strong>Category:</strong>{{event.category.name}} <br />
                        <strong>Place:</strong>{{event.place}} <br />
                        <strong>Address:</strong>{{event.address}} <br />
                        <strong>Initial Date:</strong>{{event.initialDate}} <br />
                        <strong>Final Date:</strong>{{event.finalDate}} <br />
                        <strong>Created By:</strong> {{ event.user.username }}</p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% else %}
        <div class="col-lg-4 col-md-2 text-right">
            <a id="signInButton" href="#signInModal" class="text-white text-decoration-none btn btn-primary m-2 shadow" data-toggle="modal"
               data-target=".bd-example-modal-sm">
                <i class="fas fa-sign-in-alt"></i>&nbsp;Sign in
            </a>
            <a href="{% url 'events:signUp' %}" class="text-white text-decoration-none btn btn-info m-2 shadow" data-toggle="modal">
                <i class="fas fa-user-plus"></i>&nbsp;Sign up
            </a>
        </div>
        {% endif %}
    </div>

    <!-- Modal Sign in -->
    <div id="signInModal" class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header" style="background-color: #343a40">
                    <h5 class="modal-title text-white" id="exampleModalLongTitle">Sign in</h5>
                    <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'events:index' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Email</label>
                            {{form.username}}
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            {{form.password}}
                        </div>
                        <div class="text-center">
                            <button class="btn btn-success" type="submit"><i class="fas fa-sign-in-alt"></i>&nbsp;Sign
                                in</button>
                        </div>
                    </form>
                    {% if error != '' %}
                    <hr />
                    <div class="alert alert-danger text-center small" role="alert">
                        {{error}}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</body>

</html>

events/templates/events/register_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossorigin="anonymous">
</head>

<body>
    <div class="bg-dark">
        <h1 class="text-center pt-2 pb-2" style="font-family: fantasy; color: white">Register</h1>
    </div>
    <br />
    <div class="container center">
        {% block content %}
        <form action="{% url 'events:signUp' %}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <p>
                {% if field.id_for_label == 'id_username' %}
                Email:
                {% else %}
                {{ field.label_tag }}<br>
                {% endif %}
                {{ field }}
                {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
            </p>
            {% endfor %}

            <div class="form-group" align="center">
                <button class="btn btn-outline-info" type="submit">Register</button>
                <a href="/"><button type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button></a>
                <div class="border-top pt-3">
                    <small class="text-muted"> Already have an account? <a class="ml-2" href="{% url 'events:index' %}" data-toggle="modal" data-dismiss="modal">Sign In</a></small>
                </div>
            </div>
        </form>
        {% endblock %}
    </div>
</body>

</html>